### ISSUE TITLE
Memory leak when invoking compiled templates

### ISSUE THREAD

**Issue by AnirudhaGohokar** [handlebars-lang/handlebars.js#1885] opened 2022-09-16 04:50 UTC
Hi,

Invoking compiled templates is leaking memory in our nodejs service. We are able to reproduce by calling invoking compiled template of size 32kb for over 4000 iterations per minute. This hardly generates 150 mb data per min which should ideally be garbage collected but infact it doesnt and eventually after 5mins , memory utilisation goes over 1G.

This is how we are using the method:
```
const hbar = require("handlebars");
return {
        "template": hbar.compile(template, { strict: checkstrict })(templateData, { data: { intl: intlData } }),
        "subject": hbar.compile(subject, { strict: checkstrict })(templateData, { data: { intl: intlData } })
    }
```

**Comment by AnirudhaGohokar** [comment] 2022-09-16 06:52
Memory leak gone after switching to [mustache.js](https://github.com/janl/mustache.js/) since its similar to handlebars. This confirms that there's a serious memory leak happening for > 32kb data. Please look into it.

**Comment by AnirudhaGohokar** [comment] 2022-09-16 07:01
https://github.com/handlebars-lang/handlebars.js/issues/271#issue-5437561

**Comment by jaylinski** [comment] 2022-09-16 16:31
I guess this also happens with the latest Nodejs release? (18.9.0)

**Comment by AnirudhaGohokar** [comment] 2022-09-16 18:10
Hey, Yes i have tested it with latest node release (18.9.0). Issue is easy to reproduce by just iterating over the compile and rendering part for N iterations. Memory steadily rises over a period of time unless you stop the execution.

**Comment by ccapndave** [comment] 2022-10-10 14:04
I'm also experiencing this, and its causing our servers to run out of memory and crash.  The issue seemed to start when we upgraded from Node 14.20.1 to 16.17.1.  There is a discussion at https://github.com/facebook/jest/issues/11956 which may be relevant.

**Comment by ccapndave** [comment] 2022-11-15 08:07
This is absolutely a showstopper for us.  Does anyone have any ideas of a fix or even a workaround?

**Comment by ccapndave** [comment] 2022-11-15 12:08
After a lot of fiddling about, I am extremely happy to say that the problem was actually to do with the way that we were bundling and running the app containing Handlebars, and not anything to do with Handlebars itself.

**Comment by sergehuber** [comment] 2023-05-31 08:58
Maybe you could close this issue ?

**Comment by ccapndave** [comment] 2023-05-31 09:02
From my side its fine (the memory leak was my fault and not Handlebar's) but I don't know if @AnirudhaGohokar was experiencing the same issue as me.

**Closed** 2023-05-31 10:18 UTC
Labels: needs investigation

**Comment by raukaute** [comment] 2024-07-01 21:13
> After a lot of fiddling about, I am extremely happy to say that the problem was actually to do with the way that we were bundling and running the app containing Handlebars, and not anything to do with Handlebars itself. Apologies if anyone has investigated this.

Hey, can you provide a bit of details what was the cause in your case? Cheers
