### ISSUE TITLE
Allow underscore "_" is file names.

### ISSUE THREAD

**Issue by SirWumpus** [handlebars-lang/handlebars.js#1730] opened 2021-01-14 13:30 UTC
I had wanted to name some of my views and partials using underscore `_` in the file name, but when I do I get an error like:
```
unable to render view: entryUpdate because The partial entry_form could not be found
```
If I rename the `entry_form.hbs` to `entryForm.hbs` it all works.  Underscore is a very common character allowed in Javascript (C, Java, ...) identifiers and Unix / Windows file names and I see no reason exclude it.

**Comment by jaylinski** [comment] 2021-12-30 00:42
@SirWumpus Underscores seem to work just fine:

https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%3Enew_partial%7D%7D%5Cn%22%2C%22partials%22%3A%5B%7B%22name%22%3A%22new_partial%22%2C%22content%22%3A%22%3Cp%3E%7B%7Bfirstname%7D%7D%3C%2Fp%3E%22%7D%5D%2C%22input%22%3A%22%7B%5Cn%20%20firstname%3A%20%5C%22Yehuda%5C%22%2C%5Cn%7D%5Cn%22%2C%22output%22%3A%22%3Cp%3EYehuda%3C%2Fp%3E%22%2C%22preparationScript%22%3A%22%22%2C%22handlebarsVersion%22%3A%224.7.7%22%7D

Can you provide me with minimal reproduction of your issue?

**Comment by jaylinski** [comment] 2022-05-20 19:43
Closing because issue-creator is not responding.

**Closed by jaylinski** 2022-05-20 19:43 UTC
