### ISSUE TITLE
using each twice with a inner child array error

### ISSUE THREAD

**Issue by hxgqh** [handlebars-lang/handlebars.js#1833] opened 2022-03-06 11:05 UTC
data like thie:

```javascript
[{
   name: 'name',
   subArr: [{
      name: 'name1',
      code: 'code1'
   }]
}]
```

template like this:

```hbs
{{#each items}}
  {{ name }}
  {{#each subArr}}
  {{ name }}
  {{/each}}
{{/each}}

{{#each items}}
  {{ name }}
  {{#each subArr}}
  {{ code }}
  {{/each}}
{{/each}}
```

render result in the second "each" block, subArr.code will not be rendered.

**Comment by Baertie** [comment] 2022-12-14 11:48
Any update?

**Comment by jaylinski** [comment] 2022-12-14 22:06
I just tested this and it seems to work fine:
https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23each%20items%7D%7D%5Cn%20%20%7B%7B%20name%20%7D%7D%5Cn%20%20%7B%7B%23each%20subArr%7D%7D%5Cn%20%20%7B%7B%20name%20%7D%7D%5Cn%20%20%7B%7B%2Feach%7D%7D%5Cn%7B%7B%2Feach%7D%7D%5Cn%5Cn%7B%7B%23each%20items%7D%7D%5Cn%20%20%7B%7B%20name%20%7D%7D%5Cn%20%20%7B%7B%23each%20subArr%7D%7D%5Cn%20%20%7B%7B%20code%20%7D%7D%5Cn%20%20%7B%7B%2Feach%7D%7D%5Cn%7B%7B%2Feach%7D%7D%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20items%3A%20%5B%7B%5Cn%20%20%20%20name%3A%20'name'%2C%5Cn%20%20%20%20subArr%3A%20%5B%7B%5Cn%20%20%20%20%20%20name%3A%20'name1'%2C%5Cn%20%20%20%20%20%20code%3A%20'code1'%5Cn%20%20%20%20%7D%5D%5Cn%20%20%7D%5D%5Cn%7D%22%2C%22output%22%3A%22%20%20name%5Cn%20%20name1%5Cn%5Cn%20%20name%5Cn%20%20code1%5Cn%22%2C%22preparationScript%22%3A%22%22%2C%22handlebarsVersion%22%3A%224.7.7%22%7D

Are you using the latest version?

**Comment by jaylinski** [comment] 2023-08-03 23:35
Closing because can't reproduce. If this is still relevant, please reopen.

**Closed by jaylinski** 2023-08-03 23:35 UTC
Labels: needs investigation
